### PR TITLE
Playlist management

### PR DESCRIPTION
**Pull request by AtulPant2704**
- Made Playlist Modal and Single Playlist Page screen.
- Made context for Playlist Modal and Video on which user has clicked.
- Make a new Playlist, delete a Playlist, add videos to the playlist, remove videos from playlist functionality applied.
- Users can add or remove a video from the playlist, from the Video Listing page itself.

Preview:- https://deploy-preview-6--checkmate-stream.netlify.app/explore

`Note:- Watch later Playlist won't work as of now, I will work on it later, you can create any new Playlist and then add videos to it.`

### CODE REVIEW

**Review by mohammed-sas — APPROVED** [review]
Code is clean and readable
Playlist modal ui is great
adding and removing from playlist works fine
PlaylistHandler functions are defined well in seperate folders
Pr is good to merge

**Review by Abhijeet43 — APPROVED** [review]
The functionality is working fine!!!!
UI is also good!!!

**Comment by AnkurChunekar** [comment]
atul pr

- Functionality works well, but user can create more than one playlist with the same name that might create confusion.
- Playlist is also created for an empty input (name).

**Review by AnkurChunekar — APPROVED** [review]

**Comment by AnkurChunekar** [comment]
All the required edge cases have been handled, great work @AtulPant2704

**Pull request merged**
