### PR TITLE
Add toast, Refactor Imports, Removed Videos from context

### PR DESCRIPTION
**Pull request by AtulPant2704**
- Add toast for user actions
- Refactor import structure
- Videos fetched only from Video Listing page
- Moved Backdrop In Playlist Modal file
- Add loader on Video listing page while Videos are getting fetched

Preview:- https://deploy-preview-11--checkmate-stream.netlify.app/explore

`Note:- So many lines changes are not actual lines, those are imported from react-toastify.`

### CODE REVIEW

**Review by RakshaPawar108 — COMMENTED** [review]
All functionalities are working fine Atul. 
Just a bug that I found is that when I log in, the UI does not let me know if I am logged in or not. I am able to see the toast which says successfully logged in. But I am able to still see the login button on the navbar and if I click on that, the toast says you are not logged in. But even then I am able to play the videos. Can you please check that?

**Comment by AtulPant2704** [comment]
> All functionalities are working fine Atul. Just a bug that I found is that when I log in, the UI does not let me know if I am logged in or not. I am able to see the toast which says successfully logged in. But I am able to still see the login button on the navbar and if I click on that, the toast says you are not logged in. But even then I am able to play the videos. Can you please check that?

Thanks for pointing it out, I have fixed that issue, can you check now.

**Review by RakshaPawar108 — APPROVED** [review]
Works fine now Atul! The toasts look great and enhance the UX. Great work!!

**Review by AnkurChunekar — APPROVED** [review]
Code looks neat and clean, great work @AtulPant2704

**Pull request merged**
